# Generated by Django 3.2.7 on 2021-12-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20211209_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photo/'),
        ),
    ]
